---
- hosts: build
  vars:
    jenkins_hostname: localhost
  tasks:
    - name: install git
      yum:
        name=git
        state=present
    - name: install maven
      yum:
        name=maven
        state=present
    - name: start jenkins
      service:
        name: jenkins
        state: started
    - name: install jenkins plugin github
      jenkins_plugin:
        name: github
        url_username: admin
        url_password: admin
    - name: install jenkins plugin publish over ssh
      jenkins_plugin:
        name: publish-over-ssh
        url_username: admin
        url_password: admin
  roles:
    - role: geerlingguy.java
      when: "ansible_os_family == 'RedHat'"
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.jenkins
- hosts: live
  roles:
    - role: inkatze.wildfly
